baseURL = 'https://maysaclaudino.github.io/'
languageCode = 'pt-br'
title = 'Maysa Claudino'
theme = 'quint'

summaryLength = 5                  # Number of characters in your card summaries

[[menu.main]]
    name = "TCC"
    url = "/tcc"
    weight = 10

[params]
contact = "You can write me an [email](mailto:maysaclaudino@usp.br)."

[[params.social]]
    url = "mailto:maysaclaudino@usp.br"
    icon = "/social/email.png"
    name = "Email"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
